# Generated by Django 5.2.8 on 2025-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('message_received', 'Message Received'), ('chat_started', 'Chat Started'), ('saved_search_match', 'Saved Search Match')], max_length=20),
        ),
    ]
